<<<<<<< HEAD
# Generated by Django 5.2.10 on 2026-01-13 10:18

import common.fields
import django.core.validators
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields
from decimal import Decimal
=======
# Generated by Django 5.0.1 on 2026-01-13 10:26

>>>>>>> origin/jules/phase1-foundation-10297780927730413954
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Lender's name for this address", max_length=255)),
                ('street_1', models.CharField(blank=True, help_text='Street address line 1', max_length=255, null=True)),
                ('street_2', models.CharField(blank=True, help_text='Street address line 2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=255, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, help_text='State', max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, help_text='ZIP code', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text='Legal name of the lending company', max_length=500)),
                ('include_states', common.fields.ChoiceArrayField(base_field=localflavor.us.models.USStateField(max_length=2), default=list, help_text='States where this lender is licensed to operate', size=None)),
                ('company_website', models.URLField(blank=True, help_text="Lender's main website URL", null=True)),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Main company phone number', max_length=128, null=True, region=None)),
                ('company_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Main company fax number', max_length=128, null=True, region=None)),
                ('company_email', models.EmailField(blank=True, help_text='General company email address', max_length=254, null=True)),
                ('company_notes', models.TextField(blank=True, help_text='Internal notes about this lender', null=True)),
            ],
            options={
                'verbose_name': 'Lender',
                'verbose_name_plural': 'Lenders',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Program name (e.g., 'DSCR Investor', 'FHA')", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('agency', 'Agency/Conventional'), ('non_qm', 'Non-QM'), ('hard_money', 'Hard Money/Bridge'), ('commercial', 'Commercial')], help_text='Program category for grouping', max_length=20)),
                ('loan_type', models.CharField(choices=[('conventional', 'Conventional'), ('Alt-A', 'ALT A'), ('hard money', 'Hard Money'), ('construction', 'Construction'), ('fix and flip', 'Fix and Flip')], default='conventional', help_text='Type of loan', max_length=15)),
                ('property_types', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15), default=list, help_text='Allowed property types', size=None)),
                ('income_type', models.CharField(choices=[('full', 'Full Income Documents (Taxes, Pay stubs)'), ('stated', 'Stated (Low doc or no doc)')], default='stated', help_text='Income documentation type', max_length=30)),
                ('documentation_level', models.CharField(choices=[('full', 'Full Documentation'), ('lite', 'Lite Documentation'), ('no_doc', 'No Documentation'), ('bank_statement', 'Bank Statement'), ('dscr', 'DSCR Only'), ('asset', 'Asset Depletion')], default='full', help_text='Documentation level required', max_length=20)),
                ('base_min_fico', models.PositiveSmallIntegerField(default=620, help_text='Base minimum FICO score', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('base_max_ltv', models.FloatField(default=80, help_text='Base maximum LTV percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_min_dscr', models.FloatField(blank=True, help_text='Base minimum DSCR for rental income programs', null=True)),
                ('occupancy', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('owner occupied', 'Owner Occupied'), ('second home', 'Second Home'), ('investment', 'Investment')], max_length=15), default=list, help_text='Allowed occupancy types', size=None)),
                ('entity_types', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('individual', 'Individual'), ('non-profit', 'Non Profit'), ('c-corp', 'C Corporation'), ('s-corp', 'S Corporation'), ('partnership', 'Partnership'), ('trust', 'Trust'), ('LLC', 'LLC'), ('foreign national', 'Foreign National'), ('foreign corp', 'Foreign Corp'), ('other', 'Other')], max_length=20), default=list, help_text='Allowed borrowing entity types', size=None)),
                ('purposes', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('fix and flip', 'Fix and Flip'), ('raw land', 'Raw Land'), ('construction', 'Construction'), ('equity share', 'Equity Share')], max_length=12), default=list, help_text='Allowed loan purposes', size=None)),
                ('description', models.TextField(blank=True, help_text='Program guidelines summary')),
                ('is_active', models.BooleanField(default=True, help_text='Is this program type active?')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Sort order for display')),
            ],
            options={
                'verbose_name': 'Program Type',
                'verbose_name_plural': 'Program Types',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LenderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(blank=True, help_text="Contact person's name", max_length=100, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('owner', 'Owner'), ('account exec', 'Account Executive'), ('processor', 'Processor'), ('underwriter', 'Underwriter'), ('closer', 'Closer')], default='owner', help_text='Role or position of this contact', max_length=25, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Contact's phone number", max_length=128, null=True, region=None)),
                ('contact_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Contact's fax number", max_length=128, null=True, region=None)),
                ('contact_email', models.CharField(blank=True, help_text="Contact's email address", max_length=100, null=True)),
                ('address', models.ForeignKey(help_text='Physical address of this contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender_contacts', to='pricing.addressinfo')),
                ('lender', models.ForeignKey(help_text='Lender this contact works for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pricing.lender')),
            ],
            options={
                'verbose_name': 'Lender Contact',
                'verbose_name_plural': 'Lender Contacts',
            },
        ),
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Loan program name', max_length=500)),
                ('loan_type', models.CharField(choices=[('conventional', 'Conventional'), ('Alt-A', 'ALT A'), ('hard money', 'Hard Money'), ('construction', 'Construction'), ('fix and flip', 'Fix and Flip')], default='conventional', help_text='Type of loan program', max_length=15)),
                ('income_type', models.CharField(choices=[('full', 'Full Income Documents (Taxes, Pay stubs)'), ('stated', 'Stated (Low doc or no doc)')], default='stated', help_text='Income documentation required', max_length=30)),
                ('occupancy', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('owner occupied', 'Owner Occupied'), ('second home', 'Second Home'), ('investment', 'Investment')], help_text='Occupancy type', max_length=15), default=list, help_text='Allowed occupancy types', size=None)),
                ('property_types', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15), default=list, help_text='Allowed property types (residential, commercial)', size=None)),
                ('property_sub_categories', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('single family', 'Single-family residence'), ('2-4 unit residential', '2-4 unit residential'), ('condo townhomes', 'Condominiums and townhomes'), ('non-warrantable condo', 'Non-warrantable condominiums'), ('manufactured', 'Mobile/manufactured homes'), ('5+ units', '5+ Units (Multi-family)'), ('office', 'Office'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('hospitality', 'Hospitality (hotels and motels)'), ('self storage', 'Self-storage'), ('mixed use', 'Mixed-use'), ('land', 'Land and/or lot'), ('other', 'Other')], max_length=25), default=list, help_text='Specific property sub-types allowed', size=None)),
                ('property_conditions', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('C1', 'C1 - Excellent / New'), ('C2', 'C2 - No Damage'), ('C3', 'C3 - Little Damage'), ('C4', 'C4 - Some Damage'), ('C5', 'C5 - Obvious Damage'), ('C6', 'C6 - Severe Damage')], max_length=2), default=list, help_text='Appraisal condition ratings allowed (C1-C6)', size=None)),
                ('recourse', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('full recourse', 'Full Recourse'), ('non-recourse', 'Non Recourse')], max_length=15), default=list, help_text='Full recourse or non-recourse', size=None)),
                ('amortization_terms', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('1', '1 Year'), ('5', '5 Years'), ('10', '10 Years'), ('20', '20 Years'), ('25', '25 Years'), ('30', '30 Years'), ('40', '40 Years'), ('5/1', '5/1 ARM'), ('7/1', '7/1 ARM')], max_length=20), default=list, help_text='Available amortization periods', size=None)),
                ('io_offered', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Interest-only payment option available', verbose_name='I/O Offered')),
                ('p_and_i_offered', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Principal and interest payment option available', verbose_name='P&I Offered')),
                ('entity_type', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('individual', 'Individual'), ('non-profit', 'Non Profit'), ('c-corp', 'C Corporation'), ('s-corp', 'S Corporation'), ('partnership', 'Partnership'), ('trust', 'Trust'), ('LLC', 'LLC'), ('foreign national', 'Foreign National'), ('foreign corp', 'Foreign Corp'), ('other', 'Other')], max_length=20), default=list, help_text='Allowed borrowing entity types', size=None)),
                ('employment', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('W2', 'W2 Wage Earner'), ('self', 'Self Employed'), ('fixed', 'Fixed Income')], help_text='Employment type', max_length=10), default=list, help_text='Allowed employment types', size=None)),
                ('percent_ownership', models.PositiveSmallIntegerField(blank=True, help_text='Minimum ownership percentage required', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('purpose', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('fix and flip', 'Fix and Flip'), ('raw land', 'Raw Land'), ('construction', 'Construction'), ('equity share', 'Equity Share')], max_length=12), default=list, help_text='Approved loan purposes', size=None)),
                ('max_cash_out', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cash-out amount', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_loan_amount', models.DecimalField(decimal_places=2, help_text='Minimum loan amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_loan_amount', models.DecimalField(decimal_places=2, help_text='Maximum loan amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_loan_to_value', models.DecimalField(decimal_places=2, help_text='Maximum loan-to-value ratio', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserve_requirement', models.PositiveSmallIntegerField(help_text='Required months of reserves')),
                ('min_credit', models.PositiveSmallIntegerField(default=580, help_text='Minimum credit score required', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('min_acreage', models.PositiveSmallIntegerField(blank=True, help_text='Minimum acreage allowed', null=True)),
                ('max_acreage', models.PositiveSmallIntegerField(blank=True, help_text='Maximum acreage allowed (blank = unlimited)', null=True)),
                ('max_properties_financed', models.PositiveIntegerField(blank=True, help_text='Maximum financed properties allowed (blank = unlimited)', null=True)),
                ('refinance_seasoning', models.CharField(choices=[('0', '0 Months (Immediate)'), ('6', '6 Months'), ('12', '12 Months'), ('24', '24 Months')], help_text='Months after purchase before refinance allowed', max_length=5)),
                ('ysp_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Yield spread premium allowed', verbose_name='YSP Available')),
                ('max_ysp', models.PositiveSmallIntegerField(blank=True, help_text='Maximum YSP percentage allowed', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max YSP')),
                ('max_compensation', models.PositiveSmallIntegerField(help_text='Maximum broker compensation percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Broker processing/admin fee allowed')),
                ('max_dti', models.PositiveIntegerField(blank=True, help_text='Maximum debt-to-income ratio (blank = none)', null=True, verbose_name='Max DTI')),
                ('lender_fee', models.DecimalField(decimal_places=2, help_text='Lender underwriting/loan fee', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prepayment_penalty', models.CharField(choices=[('none', 'None'), ('1 year', '1 Year'), ('2 year', '2 Years'), ('3 year', '3 Years'), ('5 year', '5 Years')], help_text='Prepayment penalty options', max_length=10)),
                ('prepayment_cost', models.CharField(choices=[('1', '1%'), ('2', '2%'), ('3', '3%'), ('4', '4%'), ('5', '5%')], help_text='Prepayment penalty percentage', max_length=4)),
                ('rate_lock_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Rate lock available')),
                ('rate_lock_terms', models.PositiveSmallIntegerField(blank=True, choices=[('15', '15 Days'), ('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days')], help_text='Rate lock period in days', null=True)),
                ('bk_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Bankruptcy allowed', verbose_name='BK Allowed')),
                ('time_since_bk', models.PositiveSmallIntegerField(blank=True, help_text='Years since bankruptcy (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since BK')),
                ('foreclosure_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Foreclosure allowed')),
                ('time_since_foreclosure', models.PositiveSmallIntegerField(blank=True, help_text='Years since foreclosure (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('short_sales_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Short sale allowed')),
                ('time_since_short_sale', models.PositiveSmallIntegerField(blank=True, help_text='Years since short sale (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nod_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Notice of Default allowed', verbose_name='NOD Allowed')),
                ('time_since_nod', models.PositiveSmallIntegerField(blank=True, help_text='Years since Notice of Default (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since NOD')),
                ('nos_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Notice of Sale allowed', verbose_name='NOS Allowed')),
                ('time_since_nos', models.PositiveSmallIntegerField(blank=True, help_text='Years since Notice of Sale (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since NOS')),
                ('potential_rate_min', models.FloatField(help_text='Approximate minimum interest rate (0-30%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_rate_max', models.FloatField(help_text='Approximate maximum interest rate', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_cost_min', models.FloatField(help_text='Minimum cost in points (lender points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_cost_max', models.FloatField(help_text='Maximum cost in points (lender points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lien_position', models.CharField(choices=[('1', '1st Mortgage'), ('2', '2nd Mortgage'), ('3', '3rd Mortgage'), ('other', 'Other')], default='other', help_text='Trust deed/mortgage lien position', max_length=5)),
                ('max_ltv_on_purchase_price', models.FloatField(blank=True, help_text='Max LTV on land value for construction loans', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max LTV on Purchase Price (%)')),
                ('max_ltv_on_arv', models.FloatField(blank=True, help_text='Max LTV on after-repair value for construction loans', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max LTV on ARV (%)')),
                ('max_ltv_on_cost', models.FloatField(blank=True, help_text='Max loan-to-cost for construction loans', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max LTV on Cost (%)')),
                ('max_ltv_on_rehab', models.FloatField(blank=True, help_text='Max LTV on construction funds for construction loans', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max LTV on Rehab Money Financed (%)')),
                ('min_borrower_contribution', models.FloatField(blank=True, help_text='Minimum borrower contribution as % of LTC', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_dscr', models.FloatField(help_text='Minimum debt service coverage ratio', verbose_name='Min DSCR')),
                ('lender', models.ForeignKey(help_text='Lender offering this program', on_delete=django.db.models.deletion.CASCADE, to='pricing.lender')),
            ],
            options={
                'verbose_name': 'Loan Program',
                'verbose_name_plural': 'Loan Programs',
                'ordering': ['lender', 'loan_type'],
            },
        ),
        migrations.CreateModel(
            name='LenderProgramOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_rate', models.FloatField(help_text='Minimum interest rate (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('max_rate', models.FloatField(help_text='Maximum interest rate (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('min_points', models.FloatField(default=0, help_text='Minimum origination points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('max_points', models.FloatField(default=2, help_text='Maximum origination points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('lender_fee', models.DecimalField(decimal_places=2, default=Decimal('995.00'), help_text='Lender underwriting fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_fico', models.PositiveSmallIntegerField(help_text="Lender's min FICO (may be higher than program base)", validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('max_ltv', models.FloatField(help_text="Lender's max LTV (may be lower than program base)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_dscr', models.FloatField(blank=True, help_text="Lender's min DSCR for rental programs", null=True)),
                ('min_loan', models.DecimalField(decimal_places=2, default=Decimal('75000.00'), help_text='Minimum loan amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_loan', models.DecimalField(decimal_places=2, default=Decimal('2000000.00'), help_text='Maximum loan amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_sheet_url', models.URLField(blank=True, help_text='URL to current rate sheet PDF')),
                ('last_rate_update', models.DateTimeField(blank=True, help_text='When rates were last updated from rate sheet', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this offering active?')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this offering')),
                ('lender', models.ForeignKey(help_text='Lender offering this program', on_delete=django.db.models.deletion.CASCADE, related_name='program_offerings', to='pricing.lender')),
                ('program_type', models.ForeignKey(help_text='Program type being offered', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='pricing.programtype')),
            ],
            options={
                'verbose_name': 'Lender Program Offering',
                'verbose_name_plural': 'Lender Program Offerings',
                'ordering': ['program_type', 'lender__company_name'],
                'unique_together': {('lender', 'program_type')},
            },
        ),
        migrations.CreateModel(
            name='RateAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('fico_ltv', 'Credit Score × LTV Grid'), ('purpose', 'Loan Purpose'), ('occupancy', 'Occupancy Type'), ('property_type', 'Property Type'), ('loan_amount', 'Loan Amount Tier'), ('lock_period', 'Rate Lock Period'), ('state', 'State')], help_text='Type of adjustment', max_length=20)),
                ('value_key', models.CharField(blank=True, help_text="Lookup key for 1D adjustments (e.g., 'purchase', 'CA')", max_length=50)),
                ('row_min', models.FloatField(blank=True, help_text='Minimum value for row dimension (e.g., min FICO)', null=True)),
                ('row_max', models.FloatField(blank=True, help_text='Maximum value for row dimension (e.g., max FICO)', null=True)),
                ('col_min', models.FloatField(blank=True, help_text='Minimum value for column dimension (e.g., min LTV)', null=True)),
                ('col_max', models.FloatField(blank=True, help_text='Maximum value for column dimension (e.g., max LTV)', null=True)),
                ('adjustment_points', models.FloatField(help_text='Adjustment in points (negative = cost, positive = credit)')),
                ('offering', models.ForeignKey(help_text='Lender program offering this adjustment applies to', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pricing.lenderprogramoffering')),
            ],
            options={
                'verbose_name': 'Rate Adjustment',
                'verbose_name_plural': 'Rate Adjustments',
                'ordering': ['offering', 'adjustment_type', 'row_min', 'col_min'],
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=500)),
            ],
            options={
                "abstract": False,
>>>>>>> origin/jules/phase1-foundation-10297780927730413954
            },
        ),
    ]
