# Generated by Django 5.0.1 on 2026-01-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("loan_type", models.CharField(blank=True, max_length=50)),
                ("property_types", models.JSONField(blank=True, default=list)),
                ("entity_types", models.JSONField(blank=True, default=list)),
                ("purposes", models.JSONField(blank=True, default=list)),
                ("occupancy", models.JSONField(blank=True, default=list)),
                ("base_min_fico", models.IntegerField(default=0)),
                ("base_max_ltv", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lender",
            name="include_states",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lender",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="LenderProgramOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_rate", models.FloatField(default=0.0)),
                ("max_rate", models.FloatField(default=0.0)),
                ("min_points", models.FloatField(default=0.0)),
                ("max_points", models.FloatField(default=0.0)),
                ("min_fico", models.IntegerField(default=0)),
                ("max_ltv", models.FloatField(default=0.0)),
                (
                    "min_loan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_loan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pricing.lender"
                    ),
                ),
                (
                    "program_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.programtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RateAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment_type", models.CharField(max_length=50)),
                ("row_min", models.FloatField(blank=True, null=True)),
                ("row_max", models.FloatField(blank=True, null=True)),
                ("col_min", models.FloatField(blank=True, null=True)),
                ("col_max", models.FloatField(blank=True, null=True)),
                ("adjustment_points", models.FloatField(default=0.0)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="pricing.lenderprogramoffering",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
