# Generated by Django 5.2.10 on 2026-01-16 21:11

import django.core.validators
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualifyingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        help_text="Type of property",
                        max_length=15,
                    ),
                ),
                (
                    "occupancy",
                    models.CharField(
                        choices=[
                            ("owner occupied", "Owner Occupied"),
                            ("second home", "Second Home"),
                            ("investment", "Investment"),
                        ],
                        help_text="Occupancy type",
                        max_length=15,
                    ),
                ),
                (
                    "state",
                    localflavor.us.models.USStateField(
                        help_text="Property state", max_length=2
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("refinance", "Refinance"),
                            ("fix and flip", "Fix and Flip"),
                            ("raw land", "Raw Land"),
                            ("construction", "Construction"),
                            ("equity share", "Equity Share"),
                        ],
                        help_text="Loan purpose",
                        max_length=12,
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Requested loan amount",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ltv",
                    models.FloatField(
                        help_text="Loan-to-Value ratio (%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("non-profit", "Non Profit"),
                            ("c-corp", "C Corporation"),
                            ("s-corp", "S Corporation"),
                            ("partnership", "Partnership"),
                            ("trust", "Trust"),
                            ("LLC", "LLC"),
                            ("foreign national", "Foreign National"),
                            ("foreign corp", "Foreign Corp"),
                            ("other", "Other"),
                        ],
                        help_text="Borrowing entity type",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_credit_score",
                    models.PositiveSmallIntegerField(
                        help_text="Estimated credit score",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualifying Info",
                "verbose_name_plural": "Qualifying Infos",
                "ordering": ["-created_at"],
            },
        ),
    ]
