import requests
from cms.models import ProgramPage, BlogPage
# Setup django environment if executed as script
import os
import django
import sys
from pathlib import Path

# Add backend to path - assuming script is in /app/scripts/ and project root is /app/
# verify_url_parity.py is in scripts/
root_path = Path(__file__).resolve().parent.parent
sys.path.append(str(root_path)) # /app/
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.local')
django.setup()

def get_wordpress_urls():
    """Fetch URLs from expected list or sitemap stub."""
    # Since we can't easily fetch live sitemap without internet sometimes, 
    # we can use the url_mapping.csv generated by F.2 extractor if exists
    
    # If running in Docker (CWD=/app), path is wp_export/url_mapping.csv
    # If running locally from repo root, path is unified-platform/backend/wp_export/url_mapping.csv
    
    potential_paths = [
        Path('wp_export/url_mapping.csv'),  # Docker /app relative
        Path('unified-platform/backend/wp_export/url_mapping.csv'), # Host repo root
        Path('../wp_export/url_mapping.csv'), # From scripts dir
    ]
    
    mapping_path = None
    for p in potential_paths:
        if p.exists():
            mapping_path = p
            break
            
    urls = set()
    
    if mapping_path:
        import csv
        with open(mapping_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # new_url e.g /programs/fha-loans/
                # We want just the path
                urls.add(row['new_url'].strip('/'))
    else:
        print("Warning: url_mapping.csv not found, cannot verify full parity list.")
    
    return urls

def get_wagtail_urls():
    """Get URLs from Wagtail pages."""
    urls = set()
    
    # We want the relative path from root, e.g 'programs/fha-loans'
    # Page.url usually returns full path /programs/fha-loans/
    
    for page in ProgramPage.objects.live():
        urls.add(page.url.strip('/'))
    
    for page in BlogPage.objects.live():
        urls.add(page.url.strip('/'))
    
    return urls

def compare_urls():
    """Compare intended URLs vs actual Wagtail URLs."""
    intended_urls = get_wordpress_urls()
    actual_urls = get_wagtail_urls()
    
    if not intended_urls:
         print("No intended URLs found to compare.")
         return False

    missing = intended_urls - actual_urls
    extra = actual_urls - intended_urls
    
    print(f"Intended URLs (from Export): {len(intended_urls)}")
    print(f"Actual Wagtail URLs: {len(actual_urls)}")
    
    # Filter out funded loans if not in comparison scope?
    # The get_wordpress_urls includes funded loans if they were in CSV.
    # get_wagtail_urls only checked Program and Blog.
    # Let's verify if csv has funded-loan type
    
    print(f"\nMissing from Wagtail: {len(missing)}")
    for url in sorted(missing)[:10]:
        print(f"  - {url}")
    
    print(f"\nExtra in Wagtail: {len(extra)}")
    for url in sorted(extra)[:10]:
        print(f"  + {url}")
    
    if not missing:
        print("\n✅ URL PARITY ACHIEVED (All exported URLs exist in Wagtail)")
        return True
    else:
        print(f"\n❌ URL mismatch: {len(missing)} missing")
        return False

if __name__ == '__main__':
    compare_urls()
