# Generated by Django 5.2.10 on 2026-01-14 00:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedLoanIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True)),
                ('hero_cta_text', models.CharField(blank=True, default='Get Your Quote', max_length=100)),
                ('hero_cta_url', models.URLField(blank=True, default='/quote')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegacyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegacyRecreatedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('original_url', models.URLField(help_text='Original URL from custommortgageinc.com')),
                ('original_title', models.CharField(max_length=500)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('raw_html', models.TextField(blank=True, help_text='Original HTML content')),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FundedLoanPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('program_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('hard_money', 'Hard Money'), ('nonqm', 'NonQM Stated No Doc No Income'), ('reverse_mortgage', 'Reverse Mortgage')], default='residential', max_length=50)),
                ('mortgage_program_highlights', wagtail.fields.RichTextField(blank=True)),
                ('details_about_mortgage_loan_program', wagtail.fields.RichTextField(blank=True)),
                ('benefits_of', wagtail.fields.RichTextField(blank=True)),
                ('requirements', wagtail.fields.RichTextField(blank=True)),
                ('how_to_qualify_for', wagtail.fields.RichTextField(blank=True)),
                ('why_us', wagtail.fields.RichTextField(blank=True)),
                ('program_faq', wagtail.fields.RichTextField(blank=True)),
                ('interest_rates', models.CharField(blank=True, help_text='e.g., 5.50-8.25%', max_length=100)),
                ('minimum_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_credit_score', models.IntegerField(blank=True, null=True)),
                ('max_ltv', models.CharField(blank=True, help_text='e.g., 96.5%', max_length=20)),
                ('max_debt_to_income_ratio', models.FloatField(blank=True, null=True)),
                ('min_dscr', models.FloatField(blank=True, help_text='For DSCR programs', null=True)),
                ('property_types', models.JSONField(blank=True, default=list, help_text='List of property types')),
                ('occupancy_types', models.JSONField(blank=True, default=list)),
                ('lien_position', models.JSONField(blank=True, default=list)),
                ('amortization_terms', models.JSONField(blank=True, default=list)),
                ('purpose_of_mortgage', models.JSONField(blank=True, default=list)),
                ('refinance_types', models.JSONField(blank=True, default=list)),
                ('income_documentation_type', models.JSONField(blank=True, default=list)),
                ('prepayment_penalty', models.CharField(blank=True, max_length=100)),
                ('borrower_types', models.JSONField(blank=True, default=list)),
                ('citizenship_requirements', models.JSONField(blank=True, default=list)),
                ('credit_events_allowed', models.JSONField(blank=True, default=list)),
                ('mortgage_lates_allowed', models.JSONField(blank=True, default=list)),
                ('is_local_variation', models.BooleanField(default=False)),
                ('target_city', models.CharField(blank=True, max_length=100)),
                ('target_state', models.CharField(blank=True, max_length=2)),
                ('local_office_address', models.TextField(blank=True)),
                ('local_phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('schema_markup', models.JSONField(blank=True, help_text='Structured data for SEO', null=True)),
                ('source_url', models.URLField(blank=True, help_text='Original WordPress URL for reference')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
