# Generated by Django 5.2.10 on 2026-01-14 01:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundedloanpage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original WordPress URL for reference'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='what_are',
            field=wagtail.fields.RichTextField(blank=True, help_text="What are these loans? (e.g., 'What are Super Jumbo Loans?')"),
        ),
    ]
