# Generated by Django 5.2.10 on 2026-01-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_fundedloanpage_source_url_programpage_what_are"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zipcode", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude for proximity calculations",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude for proximity calculations",
                        max_digits=9,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False,
                        help_text="Fallback office if city > 500 miles from nearest",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "ordering": ["state", "city"],
            },
        ),
    ]
