# Generated by Django 5.2.10 on 2026-01-14 23:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_fundedloanpage_source_url_programpage_what_are"),
        ("pricing", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="local_office_address",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="local_phone",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="program_faq",
        ),
        migrations.AddField(
            model_name="programpage",
            name="faq",
            field=wagtail.fields.StreamField(
                [("faq_item", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("answer", 1)]],
                        {"icon": "help"},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="linked_program_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to pricing engine program type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.programtype",
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="target_region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("author", models.CharField(max_length=100)),
                ("intro", models.TextField(blank=True)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
