# Generated by Django 5.2.10 on 2026-01-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_blogindexpage_remove_programpage_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programpage",
            name="available_states",
            field=models.JSONField(
                blank=True, default=list, help_text="List of available state codes"
            ),
        ),
    ]
