# Generated by Django 5.2.10 on 2026-01-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_office'),
        ('cms', '0004_programpage_available_states'),
    ]

    operations = [
    ]
