# Generated by Django 5.2.10 on 2026-01-16 11:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_merge_0003_office_0004_programpage_available_states'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('median_income', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'indexes': [models.Index(fields=['state'], name='cms_city_state_a7a24c_idx'), models.Index(fields=['slug'], name='cms_city_slug_1aa1a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('local_intro', models.TextField(blank=True, help_text='AI-generated 200-word intro')),
                ('local_faqs', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})})),
                ('assigned_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_pages', to='cms.office')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_pages', to='cms.city')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_pages', to='cms.programpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
