# Generated by Django 5.2.10 on 2026-01-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_city_localprogrampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localprogrampage',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_pages', to='cms.city'),
        ),
        migrations.AlterField(
            model_name='localprogrampage',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_pages', to='cms.programpage'),
        ),
    ]
