# Generated by Django 5.2.10 on 2026-01-18 19:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_localprogrampage_city_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.CharField(max_length=300)),
                ('second_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('phone', models.CharField(default='866-976-5669', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for maps and proximity', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for maps and proximity', max_digits=9, null=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory paragraph for this location')),
                ('nearest_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pages', to='cms.office')),
            ],
            options={
                'verbose_name': 'Location Page',
                'verbose_name_plural': 'Location Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
