# Generated by Django 5.2.10 on 2026-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_location_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
