# Generated by Django 5.2.10 on 2026-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_zipcode_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='localprogrampage',
            name='schema_markup',
            field=models.JSONField(blank=True, help_text='Auto-generated JSON-LD schema', null=True),
        ),
    ]
