# Generated by Django 5.2.10 on 2026-01-20 01:11

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_localprogrampage_schema_markup'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('items', wagtail.fields.StreamField([('link', 4), ('sub_menu', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display for the link', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL (e.g., https://google.com)', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal Page Link', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('link_text', 0), ('link_url', 1), ('link_page', 2), ('open_in_new_tab', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.ListBlock', (4,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 6)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_cms_navigationmenu')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('site_name', models.CharField(default='Custom Mortgage', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_cms_siteconfiguration')],
            },
        ),
    ]
