# Generated by Django 5.2.10 on 2026-01-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_navigationmenu_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Override authentication items with raw HTML. Takes precedence over items.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_raw_html',
            field=models.TextField(blank=True, help_text='Override entire footer with raw HTML.'),
        ),
    ]
