# Generated by Django 5.2.10 on 2026-01-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_featuredprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority'),
        ),
    ]
