# Generated by Django 5.2.10 on 2026-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_city_launched_at_city_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOContentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title_tag', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('h1_header', models.CharField(max_length=255)),
                ('content_body', models.TextField(help_text='HTML or Markdown content')),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text='Parameters used to generate this content')),
            ],
            options={
                'verbose_name_plural': 'SEO Content Caches',
                'indexes': [models.Index(fields=['url_path'], name='cms_seocont_url_pat_a84237_idx')],
            },
        ),
    ]
