# Generated by Django 5.2.10 on 2026-01-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_seocontentcache'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='cms_city_state_a7a24c_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='cms_city_slug_1aa1a8_idx',
        ),
        migrations.AddField(
            model_name='programpage',
            name='legacy_id',
            field=models.IntegerField(blank=True, help_text='Legacy ID from old system (e.g. 9101) to identify canonical programs', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='priority',
            field=models.IntegerField(default=999, help_text='Lower number = higher priority'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('slug', 'state')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'slug'], name='cms_city_state_fd999f_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['priority'], name='cms_city_priorit_16a27c_idx'),
        ),
    ]
