# Generated by Django 5.2.10 on 2026-01-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('current_address_street', models.CharField(blank=True, max_length=255)),
                ('current_address_city', models.CharField(blank=True, max_length=100)),
                ('current_address_state', models.CharField(blank=True, max_length=2)),
                ('current_address_zip', models.CharField(blank=True, max_length=10)),
                ('years_at_current', models.FloatField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floify_loan_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=50)),
                ('property_address', models.TextField(blank=True)),
                ('property_state', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('underwriting', 'Underwriting')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Declarations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outstanding_judgments', models.BooleanField(default=False)),
                ('bankruptcy_past_7_years', models.BooleanField(default=False)),
                ('foreclosure_past_7_years', models.BooleanField(default=False)),
                ('party_to_lawsuit', models.BooleanField(default=False)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='open_los.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=255)),
                ('full_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('years_on_job', models.FloatField(default=0)),
                ('is_self_employed', models.BooleanField(default=False)),
                ('base_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='open_los.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiabilityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liability_type', models.CharField(choices=[('Revolving', 'Revolving (Credit Card)'), ('Installment', 'Installment (Car/Student Loan)'), ('Mortgage', 'Mortgage'), ('Other', 'Other')], max_length=50)),
                ('creditor_name', models.CharField(max_length=255)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('unpaid_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_be_paid_off', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='open_los.borrower')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='open_los.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='open_los.loanapplication'),
        ),
        migrations.CreateModel(
            name='AssetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('Checking', 'Checking Account'), ('Savings', 'Savings Account'), ('Retirement', 'Retirement Fund'), ('Stock', 'Stocks/Bonds'), ('Other', 'Other')], max_length=50)),
                ('financial_institution', models.CharField(max_length=255)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('cash_or_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='open_los.borrower')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='open_los.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
