# Generated by Django 5.2.10 on 2026-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_los', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('citizen', 'US Citizen'), ('permanent_alien', 'Permanent Resident Alien'), ('non_permanent_alien', 'Non-Permanent Resident Alien')], max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
