# Generated by Django 5.2.10 on 2026-01-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floify_id', models.CharField(db_index=True, help_text='Floify prospect ID', max_length=100, unique=True)),
                ('floify_loan_id', models.CharField(blank=True, db_index=True, help_text='Floify loan ID (when prospect converts to loan)', max_length=100)),
                ('borrower_email', models.EmailField(db_index=True, help_text='Primary borrower email address', max_length=254)),
                ('borrower_first_name', models.CharField(max_length=100)),
                ('borrower_last_name', models.CharField(max_length=100)),
                ('borrower_phone', models.CharField(blank=True, help_text='Mobile phone number', max_length=20)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Requested loan amount', max_digits=12, null=True)),
                ('property_address', models.TextField(blank=True, help_text='Subject property address')),
                ('property_state', models.CharField(blank=True, help_text='Property state abbreviation', max_length=2)),
                ('loan_purpose', models.CharField(blank=True, help_text='purchase, refinance, cash_out, construction', max_length=50)),
                ('property_type', models.CharField(blank=True, help_text='residential, commercial, multi-family', max_length=50)),
                ('selected_program', models.CharField(blank=True, help_text='Loan program selected by borrower', max_length=255)),
                ('selected_lender', models.CharField(blank=True, help_text='Lender selected by borrower', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('underwriting', 'Underwriting'), ('approved', 'Approved'), ('clear_to_close', 'Clear to Close'), ('funded', 'Funded'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], db_index=True, default='created', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('floify_data', models.JSONField(blank=True, default=dict, help_text='Complete Floify API response')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this application')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='application_created_b96b4a_idx'), models.Index(fields=['borrower_email', 'status'], name='application_borrowe_599cd8_idx'), models.Index(fields=['floify_id'], name='application_floify__09b25b_idx')],
            },
        ),
    ]
