# Generated by Django 5.2.10 on 2026-01-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name (e.g. 'Jan 2026 Sheet')", max_length=255)),
                ('file', models.FileField(help_text='Upload rate sheet file (PDF, CSV, XLSX)', upload_to='rate_sheets/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed', null=True)),
                ('log', models.TextField(blank=True, help_text='Processing logs and errors')),
                ('lender', models.ForeignKey(help_text='Lender this rate sheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets', to='pricing.lender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
