<<<<<<< HEAD
# Generated by Django 5.2.10 on 2026-01-13 10:31
=======
# Generated by Django 5.0.1 on 2026-01-13 10:26
>>>>>>> origin/jules/phase1-foundation-10297780927730413954

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('pricing', '0001_initial'),
=======
        ("pricing", "0001_initial"),
>>>>>>> origin/jules/phase1-foundation-10297780927730413954
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Descriptive name (e.g. 'Jan 2026 Sheet')", max_length=255)),
                ('file', models.FileField(help_text='Upload rate sheet file (PDF, CSV, XLSX)', upload_to='rate_sheets/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing completed', null=True)),
                ('log', models.TextField(blank=True, help_text='Processing logs and errors')),
                ('lender', models.ForeignKey(help_text='Lender this rate sheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets', to='pricing.lender')),
            ],
            options={
                'abstract': False,
=======
            name="RateSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="rate_sheets/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("log", models.TextField(blank=True)),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_sheets",
                        to="pricing.lender",
                    ),
                ),
            ],
            options={
                "abstract": False,
>>>>>>> origin/jules/phase1-foundation-10297780927730413954
            },
        ),
    ]
