# Generated by Django 5.2.10 on 2026-01-19 01:45

import common.fields
import django.core.validators
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Please enter the lenders name', max_length=255)),
                ('street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=500)),
                ('include_states', common.fields.ChoiceArrayField(base_field=localflavor.us.models.USStateField(max_length=2), default=list, size=None)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('company_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='RateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_rate', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LenderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('own', 'Own')], default='own', max_length=25, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender_contacts', to='loans.addressinfo')),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='loans.lender')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('loan_type', models.CharField(choices=[('conventional', 'Conventional'), ('Alt-A', 'ALT A'), ('subprime', 'Subprime'), ('hard money', 'Hard Money'), ('construction', 'Construction'), ('reverse mtg', 'Reverse MTG'), ('land', 'Land'), ('fix and flip', 'Fix and Flip')], default='conventional', max_length=15)),
                ('income_type', models.CharField(choices=[('full doc', 'Full Doc'), ('stated', 'Stated Income'), ('bank statements', 'Bank Statements')], default='stated', max_length=30)),
                ('occupancy', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('owner occupied', 'Owner Occupied'), ('second home', 'Second Home'), ('investment', 'Investment')], max_length=15), default=list, size=None)),
                ('property_types', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15), default=list, size=None)),
                ('property_sub_categories', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('single family', 'Single Family'), ('multi family', 'Multi Family')], max_length=25), default=list, size=None)),
                ('property_conditions', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], max_length=2), default=list, size=None)),
                ('recourse', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('full recourse', 'Full Recourse'), ('non-recourse', 'Non Recourse')], max_length=15), default=list, size=None)),
                ('amortization_terms', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('30', '30 Year'), ('15', '15 Year')], max_length=20), default=list, size=None)),
                ('io_offered', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='I/O Offered')),
                ('p_and_i_offered', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='P&I Offered')),
                ('entity_type', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('individual', 'Individual'), ('LLC', 'LLC')], max_length=20), default=list, size=None)),
                ('employment', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('W2', 'W2'), ('self', 'Self Employed')], max_length=10), default=list, size=None)),
                ('percent_ownership', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('purpose', common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance')], max_length=12), default=list, size=None)),
                ('max_cash_out', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_loan_to_value', models.DecimalField(decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserve_requirement', models.PositiveSmallIntegerField()),
                ('min_credit', models.PositiveSmallIntegerField(default=580, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('min_acreage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_acreage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_properties_financed', models.PositiveIntegerField(blank=True, null=True)),
                ('refinance_seasoning', models.CharField(choices=[('none', 'None'), ('6 mo', '6 Months')], max_length=5)),
                ('ysp_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='YSP Available')),
                ('max_ysp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max YSP')),
                ('max_compensation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('processing_fee_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('max_dti', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max DTI')),
                ('lender_fee', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prepayment_penalty', models.CharField(choices=[('none', 'None'), ('3 yr', '3 Years')], max_length=10)),
                ('prepayment_cost', models.CharField(choices=[('none', 'None'), ('5%', '5 Percent')], max_length=4)),
                ('rate_lock_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('rate_lock_terms', models.PositiveSmallIntegerField(blank=True, choices=[(30, '30 Days'), (45, '45 Days')], null=True)),
                ('bk_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='BK Allowed')),
                ('time_since_bk', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since BK')),
                ('foreclosure_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('time_since_foreclosure', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('short_sales_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('time_since_short_sale', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nod_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='NOD Allowed')),
                ('time_since_nod', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since NOD')),
                ('nos_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='NOS Allowed')),
                ('time_since_nos', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Time since NOS')),
                ('potential_rate_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_rate_max', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_cost_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('potential_cost_max', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lien_position', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('other', 'Other')], default='other', max_length=5)),
                ('max_ltv_on_purchase_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_ltv_on_arv', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_ltv_on_cost', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_ltv_on_rehab', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_borrower_contribution', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_dscr', models.FloatField(verbose_name='Min DSCR')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.lender')),
            ],
        ),
        migrations.CreateModel(
            name='RateAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ltv', 'LTV'), ('fico', 'FICO')], max_length=20)),
                ('condition_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition_value', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_adjustment', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('price_adjustment', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('rate_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='loans.rateprogram')),
            ],
        ),
    ]
